# Generated by Django 3.1.7 on 2021-04-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historyevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devid', models.CharField(max_length=256)),
                ('maskinfo', models.CharField(max_length=256)),
                ('evtime', models.CharField(max_length=256)),
                ('hashcode', models.CharField(max_length=256)),
                ('level', models.CharField(max_length=256)),
                ('des', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='newmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgdata', models.CharField(blank=True, max_length=512, verbose_name='图像名称')),
                ('timdata', models.DateField(verbose_name='检测时间')),
                ('mapdata', models.CharField(blank=True, max_length=512, verbose_name='图像地点')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '图像',
            },
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名称')),
                ('pswd', models.CharField(max_length=64, verbose_name='用户密码')),
                ('power', models.CharField(max_length=64, verbose_name='用户权限')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='imgout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.CharField(blank=True, default='0', max_length=512, verbose_name='1类')),
                ('d2', models.CharField(blank=True, default='0', max_length=512, verbose_name='2类')),
                ('im', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.newmap')),
            ],
            options={
                'verbose_name': '图像名称',
                'verbose_name_plural': '详细信息',
            },
        ),
    ]
